// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file client-message.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file client-message.proto.
 */
export const file_client_message: GenFile =
	/*@__PURE__*/
	fileDesc(
		"ChRjbGllbnQtbWVzc2FnZS5wcm90byLMAgoNQ2xpZW50TWVzc2FnZRIrCg9yb29tSm9pblJlcXVlc3QYASABKAsyEC5Sb29tSm9pblJlcXVlc3RIABItChByb29tTGVhdmVSZXF1ZXN0GAIgASgLMhEuUm9vbUxlYXZlUmVxdWVzdEgAEi0KEGdhbWVTdGFydFJlcXVlc3QYAyABKAsyES5HYW1lU3RhcnRSZXF1ZXN0SAASKQoOZ2FtZUVuZFJlcXVlc3QYBCABKAsyDy5HYW1lRW5kUmVxdWVzdEgAEiEKCnF1aXpBbnN3ZXIYBSABKAsyCy5RdWl6QW5zd2VySAASMwoTdHVybkVuZE5vdGlmaWNhdGlvbhgGIAEoCzIULlR1cm5FbmROb3RpZmljYXRpb25IABIlCgxvdGhlck1lc3NhZ2UYByABKAsyDS5PdGhlck1lc3NhZ2VIAEIGCgR0eXBlInAKD1Jvb21Kb2luUmVxdWVzdBIMCgR0eXBlGAEgASgJEiMKBGRhdGEYAiABKAsyFS5Sb29tSm9pblJlcXVlc3QuRGF0YRoqCgREYXRhEhAKCG5pY2tuYW1lGAEgASgJEhAKCHJvb21Db2RlGAIgASgJImAKEFJvb21MZWF2ZVJlcXVlc3QSDAoEdHlwZRgBIAEoCRIkCgRkYXRhGAIgASgLMhYuUm9vbUxlYXZlUmVxdWVzdC5EYXRhGhgKBERhdGESEAoIcGxheWVySWQYASABKAkicgoQR2FtZVN0YXJ0UmVxdWVzdBIMCgR0eXBlGAEgASgJEiQKBGRhdGEYAiABKAsyFi5HYW1lU3RhcnRSZXF1ZXN0LkRhdGEaKgoERGF0YRIQCghwbGF5ZXJJZBgBIAEoCRIQCghyb29tQ29kZRgCIAEoCSJuCg5HYW1lRW5kUmVxdWVzdBIMCgR0eXBlGAEgASgJEiIKBGRhdGEYAiABKAsyFC5HYW1lRW5kUmVxdWVzdC5EYXRhGioKBERhdGESEAoIcGxheWVySWQYASABKAkSEAoIcm9vbUNvZGUYAiABKAkiZAoKUXVpekFuc3dlchIMCgR0eXBlGAEgASgJEh4KBGRhdGEYAiABKAsyEC5RdWl6QW5zd2VyLkRhdGEaKAoERGF0YRIQCghwbGF5ZXJJZBgBIAEoCRIOCgZhbnN3ZXIYAiABKAkiZgoTVHVybkVuZE5vdGlmaWNhdGlvbhIMCgR0eXBlGAEgASgJEicKBGRhdGEYAiABKAsyGS5UdXJuRW5kTm90aWZpY2F0aW9uLkRhdGEaGAoERGF0YRIQCghwbGF5ZXJJZBgBIAEoCSJpCgxPdGhlck1lc3NhZ2USDAoEdHlwZRgBIAEoCRIgCgRkYXRhGAIgASgLMhIuT3RoZXJNZXNzYWdlLkRhdGEaKQoERGF0YRIQCghwbGF5ZXJJZBgBIAEoCRIPCgdtZXNzYWdlGAIgASgJYgZwcm90bzM",
	);

/**
 * @generated from message ClientMessage
 */
export type ClientMessage = Message<"ClientMessage"> & {
	/**
	 * @generated from oneof ClientMessage.type
	 */
	type:
		| {
				/**
				 * @generated from field: RoomJoinRequest roomJoinRequest = 1;
				 */
				value: RoomJoinRequest;
				case: "roomJoinRequest";
		  }
		| {
				/**
				 * @generated from field: RoomLeaveRequest roomLeaveRequest = 2;
				 */
				value: RoomLeaveRequest;
				case: "roomLeaveRequest";
		  }
		| {
				/**
				 * @generated from field: GameStartRequest gameStartRequest = 3;
				 */
				value: GameStartRequest;
				case: "gameStartRequest";
		  }
		| {
				/**
				 * @generated from field: GameEndRequest gameEndRequest = 4;
				 */
				value: GameEndRequest;
				case: "gameEndRequest";
		  }
		| {
				/**
				 * @generated from field: QuizAnswer quizAnswer = 5;
				 */
				value: QuizAnswer;
				case: "quizAnswer";
		  }
		| {
				/**
				 * @generated from field: TurnEndNotification turnEndNotification = 6;
				 */
				value: TurnEndNotification;
				case: "turnEndNotification";
		  }
		| {
				/**
				 * @generated from field: OtherMessage otherMessage = 7;
				 */
				value: OtherMessage;
				case: "otherMessage";
		  }
		| { case: undefined; value?: undefined };
};

/**
 * Describes the message ClientMessage.
 * Use `create(ClientMessageSchema)` to create a new message.
 */
export const ClientMessageSchema: GenMessage<ClientMessage> = /*@__PURE__*/ messageDesc(file_client_message, 0);

/**
 * @generated from message RoomJoinRequest
 */
export type RoomJoinRequest = Message<"RoomJoinRequest"> & {
	/**
	 * "ROOM_JOIN_REQUEST"
	 *
	 * @generated from field: string type = 1;
	 */
	type: string;

	/**
	 * @generated from field: RoomJoinRequest.Data data = 2;
	 */
	data?: RoomJoinRequest_Data;
};

/**
 * Describes the message RoomJoinRequest.
 * Use `create(RoomJoinRequestSchema)` to create a new message.
 */
export const RoomJoinRequestSchema: GenMessage<RoomJoinRequest> = /*@__PURE__*/ messageDesc(file_client_message, 1);

/**
 * @generated from message RoomJoinRequest.Data
 */
export type RoomJoinRequest_Data = Message<"RoomJoinRequest.Data"> & {
	/**
	 * @generated from field: string nickname = 1;
	 */
	nickname: string;

	/**
	 * @generated from field: string roomCode = 2;
	 */
	roomCode: string;
};

/**
 * Describes the message RoomJoinRequest.Data.
 * Use `create(RoomJoinRequest_DataSchema)` to create a new message.
 */
export const RoomJoinRequest_DataSchema: GenMessage<RoomJoinRequest_Data> =
	/*@__PURE__*/
	messageDesc(file_client_message, 1, 0);

/**
 * @generated from message RoomLeaveRequest
 */
export type RoomLeaveRequest = Message<"RoomLeaveRequest"> & {
	/**
	 * "ROOM_LEAVE_REQUEST"
	 *
	 * @generated from field: string type = 1;
	 */
	type: string;

	/**
	 * @generated from field: RoomLeaveRequest.Data data = 2;
	 */
	data?: RoomLeaveRequest_Data;
};

/**
 * Describes the message RoomLeaveRequest.
 * Use `create(RoomLeaveRequestSchema)` to create a new message.
 */
export const RoomLeaveRequestSchema: GenMessage<RoomLeaveRequest> = /*@__PURE__*/ messageDesc(file_client_message, 2);

/**
 * @generated from message RoomLeaveRequest.Data
 */
export type RoomLeaveRequest_Data = Message<"RoomLeaveRequest.Data"> & {
	/**
	 * @generated from field: string playerId = 1;
	 */
	playerId: string;
};

/**
 * Describes the message RoomLeaveRequest.Data.
 * Use `create(RoomLeaveRequest_DataSchema)` to create a new message.
 */
export const RoomLeaveRequest_DataSchema: GenMessage<RoomLeaveRequest_Data> =
	/*@__PURE__*/
	messageDesc(file_client_message, 2, 0);

/**
 * @generated from message GameStartRequest
 */
export type GameStartRequest = Message<"GameStartRequest"> & {
	/**
	 * "GAME_START_REQUEST"
	 *
	 * @generated from field: string type = 1;
	 */
	type: string;

	/**
	 * @generated from field: GameStartRequest.Data data = 2;
	 */
	data?: GameStartRequest_Data;
};

/**
 * Describes the message GameStartRequest.
 * Use `create(GameStartRequestSchema)` to create a new message.
 */
export const GameStartRequestSchema: GenMessage<GameStartRequest> = /*@__PURE__*/ messageDesc(file_client_message, 3);

/**
 * @generated from message GameStartRequest.Data
 */
export type GameStartRequest_Data = Message<"GameStartRequest.Data"> & {
	/**
	 * @generated from field: string playerId = 1;
	 */
	playerId: string;

	/**
	 * @generated from field: string roomCode = 2;
	 */
	roomCode: string;
};

/**
 * Describes the message GameStartRequest.Data.
 * Use `create(GameStartRequest_DataSchema)` to create a new message.
 */
export const GameStartRequest_DataSchema: GenMessage<GameStartRequest_Data> =
	/*@__PURE__*/
	messageDesc(file_client_message, 3, 0);

/**
 * @generated from message GameEndRequest
 */
export type GameEndRequest = Message<"GameEndRequest"> & {
	/**
	 * "GAME_END_REQUEST"
	 *
	 * @generated from field: string type = 1;
	 */
	type: string;

	/**
	 * @generated from field: GameEndRequest.Data data = 2;
	 */
	data?: GameEndRequest_Data;
};

/**
 * Describes the message GameEndRequest.
 * Use `create(GameEndRequestSchema)` to create a new message.
 */
export const GameEndRequestSchema: GenMessage<GameEndRequest> = /*@__PURE__*/ messageDesc(file_client_message, 4);

/**
 * @generated from message GameEndRequest.Data
 */
export type GameEndRequest_Data = Message<"GameEndRequest.Data"> & {
	/**
	 * @generated from field: string playerId = 1;
	 */
	playerId: string;

	/**
	 * @generated from field: string roomCode = 2;
	 */
	roomCode: string;
};

/**
 * Describes the message GameEndRequest.Data.
 * Use `create(GameEndRequest_DataSchema)` to create a new message.
 */
export const GameEndRequest_DataSchema: GenMessage<GameEndRequest_Data> =
	/*@__PURE__*/
	messageDesc(file_client_message, 4, 0);

/**
 * @generated from message QuizAnswer
 */
export type QuizAnswer = Message<"QuizAnswer"> & {
	/**
	 * "QUIZ_ANSWER"
	 *
	 * @generated from field: string type = 1;
	 */
	type: string;

	/**
	 * @generated from field: QuizAnswer.Data data = 2;
	 */
	data?: QuizAnswer_Data;
};

/**
 * Describes the message QuizAnswer.
 * Use `create(QuizAnswerSchema)` to create a new message.
 */
export const QuizAnswerSchema: GenMessage<QuizAnswer> = /*@__PURE__*/ messageDesc(file_client_message, 5);

/**
 * @generated from message QuizAnswer.Data
 */
export type QuizAnswer_Data = Message<"QuizAnswer.Data"> & {
	/**
	 * @generated from field: string playerId = 1;
	 */
	playerId: string;

	/**
	 * @generated from field: string answer = 2;
	 */
	answer: string;
};

/**
 * Describes the message QuizAnswer.Data.
 * Use `create(QuizAnswer_DataSchema)` to create a new message.
 */
export const QuizAnswer_DataSchema: GenMessage<QuizAnswer_Data> = /*@__PURE__*/ messageDesc(file_client_message, 5, 0);

/**
 * @generated from message TurnEndNotification
 */
export type TurnEndNotification = Message<"TurnEndNotification"> & {
	/**
	 * "TURN_END_NOTIFICATION"
	 *
	 * @generated from field: string type = 1;
	 */
	type: string;

	/**
	 * @generated from field: TurnEndNotification.Data data = 2;
	 */
	data?: TurnEndNotification_Data;
};

/**
 * Describes the message TurnEndNotification.
 * Use `create(TurnEndNotificationSchema)` to create a new message.
 */
export const TurnEndNotificationSchema: GenMessage<TurnEndNotification> =
	/*@__PURE__*/
	messageDesc(file_client_message, 6);

/**
 * @generated from message TurnEndNotification.Data
 */
export type TurnEndNotification_Data = Message<"TurnEndNotification.Data"> & {
	/**
	 * @generated from field: string playerId = 1;
	 */
	playerId: string;
};

/**
 * Describes the message TurnEndNotification.Data.
 * Use `create(TurnEndNotification_DataSchema)` to create a new message.
 */
export const TurnEndNotification_DataSchema: GenMessage<TurnEndNotification_Data> =
	/*@__PURE__*/
	messageDesc(file_client_message, 6, 0);

/**
 * @generated from message OtherMessage
 */
export type OtherMessage = Message<"OtherMessage"> & {
	/**
	 * "OTHER_MESSAGE"
	 *
	 * @generated from field: string type = 1;
	 */
	type: string;

	/**
	 * @generated from field: OtherMessage.Data data = 2;
	 */
	data?: OtherMessage_Data;
};

/**
 * Describes the message OtherMessage.
 * Use `create(OtherMessageSchema)` to create a new message.
 */
export const OtherMessageSchema: GenMessage<OtherMessage> = /*@__PURE__*/ messageDesc(file_client_message, 7);

/**
 * @generated from message OtherMessage.Data
 */
export type OtherMessage_Data = Message<"OtherMessage.Data"> & {
	/**
	 * @generated from field: string playerId = 1;
	 */
	playerId: string;

	/**
	 * @generated from field: string message = 2;
	 */
	message: string;
};

/**
 * Describes the message OtherMessage.Data.
 * Use `create(OtherMessage_DataSchema)` to create a new message.
 */
export const OtherMessage_DataSchema: GenMessage<OtherMessage_Data> =
	/*@__PURE__*/
	messageDesc(file_client_message, 7, 0);
